name: Github Actions CI to build pdf from tex source, update on push.
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
      
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v2

    - name: Check `tlmgr` version
      run: tlmgr --version

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
          # The root LaTeX file to be compiled
          root_file: thanhqtran_cv.tex

          # Interpret the root_file input as bash glob pattern
          # glob_root_file: # optional

          # The working directory for this action
          # working_directory: # optional

          # The LaTeX engine to be invoked
          # compiler: # optional, default is latexmk

          # Extra arguments to be passed to the LaTeX engine
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

          # Install extra packages by apk
          # extra_system_packages: # optional

          # Install extra .ttf/.otf fonts.
          # extra_fonts: ./fonts/*.ttf

          # Arbitrary bash codes to be executed before compiling LaTeX documents
          pre_compile: tlmgr update --self --all
          
          # Arbitrary bash codes to be executed after compiling LaTeX documents
          post_compile: latexmk -c

          # Instruct latexmk to enable --shell-escape
          # latexmk_shell_escape: # optional

          # Instruct latexmk to use LuaLaTeX
          # latexmk_use_lualatex: # optional

          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true 

    - name: Check pdf file
      run: |
        file thanhqtran_cv.pdf | grep -q ' PDF '

    - name: Upload file to repository
      run: |
        git config --global user.name "thanhqtran"
        git config --global user.email "tranquangthanh.ftu@gmail.com"
        git add thanhqtran_cv.pdf
        git commit -m "commit message"
        git push
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
