name: Github Actions CI to build pdf from tex source, update on push.
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: thanhqtran_cv.tex

    - name: Check pdf file
      run: file thanhqtran_cv.pdf | grep -q ' PDF '

    - name: Upload file to repository
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "thanhqtran"
        git config --global user.email "tranquangthanh.ftu@gmail.com"
        git add thanhqtran_cv.pdf
        git commit -m "Auto-update CV PDF"
        git push
